github.com:
    users:
        Puhfy:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Puhfy
